source 'https://cdn.cocoapods.org/'
source 'https://github.com/lynx-family/Specs.git'
platform :ios, '14.0'

use_modular_headers!
use_frameworks! :linkage => :static

project 'LynxShell.xcodeproj'

target 'LynxShell' do
  # Shell 负责 Router/Runtime；地图实现由独立 LynxMapKit Module 提供。
  pod 'LynxShellKit', :path => '.'
  pod 'LynxMapKit', :path => 'LynxMapKit'
  # AMap 官方 CocoaPods CDN 尚未同步 2.12.3，使用官方下载包的本地 podspec 固定版本。
  pod 'AMapLocation', :podspec => 'LocalPods/AMapLocation.podspec'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      disable = ['-Wno-error', '-Wno-c99-designator',
                 '-Wno-deprecated-declarations', '-Wno-deprecated-implementations']
      ['OTHER_CPLUSPLUSFLAGS', 'OTHER_CFLAGS'].each do |key|
        flags = config.build_settings[key] || ['$(inherited)']
        flags = [flags] unless flags.is_a?(Array)
        config.build_settings[key] = flags + disable
      end
    end
  end
end
